export const GET_BOTTOM_TABULAR_DATA = "GET_BOTTOM_TABULAR_DATA"; 
export const SET_NEW_BOTTOM_TABULAR_ITEM = "SET_NEW_BOTTOM_TABULAR_ITEM"; 
export const GET_TOP_TABULAR_DATA = "GET_TOP_TABULAR_DATA"; 
export const SET_HEADER_TO_SAVE_MODE = "SET_HEADER_TO_SAVE_MODE";
export const SET_VISIBLE_STATUS_TOP_TABULAR_DATA = "SET_VISIBLE_STATUS_TOP_TABULAR_DATA"